var img1 = 'data1'
var img2 = 'data2'
var img3 = 'data3'

export var faceApiSearchParams = {
  "limit": 1,
  "threshold": 2,
  "groupIds": ["test1", "test2", "test3"],
}
export var faceApiParams = {
  "url": "test1",
  "mode": "test2",
  "threshold": 1,
  "serviceTimeout": 2,
  "proxy": "test3",
  "proxyPassword": "test4",
  "proxyType": 3,
  "searchParams": faceApiSearchParams,
}
export var filterObject = {
  "docIDsFilter": {
    "list": [1, 2, 3],
    "isInclude": true
  },
  "docFormatsFilter": {
    "list": [4, 5, 6],
    "isInclude": false
  },
  "docCategoriesFilter": {
    "list": [7, 8, 9],
    "isInclude": true
  },
  "docCountriesFilter": {
    "list": ["test1", "test2", "test3"],
    "isInclude": false
  },
}
export var livenessParams = {
  "checkOVI": true,
  "checkMLI": false,
  "checkHolo": true,
  "checkED": false,
  "checkBlackAndWhiteCopy": true,
  "checkDynaprint": false,
  "checkGeometry": true,
  "checkFilters": {
    "checkOVI": filterObject,
    "checkMLI": filterObject,
    "checkHolo": filterObject
  },
}
export var authenticityParams = {
  "useLivenessCheck": true,
  "checkUVLuminiscence": false,
  "checkIRB900": true,
  "checkImagePatterns": false,
  "checkFibers": true,
  "checkExtMRZ": false,
  "checkExtOCR": true,
  "checkAxial": false,
  "checkBarcodeFormat": true,
  "checkIRVisibility": false,
  "checkIPI": true,
  "checkPhotoEmbedding": false,
  "checkPhotoComparison": true,
  "checkLetterScreen": false,
  "checkSecurityText": true,
  "livenessParams": livenessParams,
  "checkFilters": {
    "checkImagePatterns": filterObject,
    "checkFibers": filterObject,
    "checkExtMRZ": filterObject
  },
}
export var glaresCheckParams = { "imgMarginPart": 0.5, "maxGlaringPart": 1.5 }
export var imageQA = {
  "dpiThreshold": 1,
  "angleThreshold": 2,
  "documentPositionIndent": 3,
  "focusCheck": true,
  "glaresCheck": false,
  "colornessCheck": true,
  "screenCapture": false,
  "expectedPass": [1, 2, 3],
  "glaresCheckParams": glaresCheckParams,
  "brightnessThreshold": 0.5,
  "occlusionCheck": true,
}
export var rfidParams = {
  "paIgnoreNotificationCodes": [1, 2, 3],
}
export var backendProcessingConfig = {
  "url": "test",
  "rfidServerSideChipVerification": true,
  "httpHeaders": { "key1": "val1", "key2": "val2", "key3": "val3" },
  "timeoutConnection": 0.5,
}
export var processParams = {
  "multipageProcessing": true,
  "debugSaveImages": false,
  "debugSaveLogs": true,
  "returnUncroppedImage": false,
  "uvTorchEnabled": true,
  "debugSaveCroppedImages": false,
  "disableFocusingCheck": true,
  "debugSaveRFIDSession": false,
  "doublePageSpread": true,
  "manualCrop": false,
  "integralImage": true,
  "returnCroppedBarcode": false,
  "checkRequiredTextFields": false,
  "depersonalizeLog": true,
  "generateDoublePageSpreadImage": false,
  "alreadyCropped": true,
  "matchTextFieldMask": false,
  "updateOCRValidityByGlare": false,
  "noGraphics": true,
  "multiDocOnImage": false,
  "forceReadMrzBeforeLocate": true,
  "parseBarcodes": false,
  "shouldReturnPackageForReprocess": true,
  "disablePerforationOCR": false,
  "respectImageQuality": true,
  "strictImageQuality": true,
  "splitNames": false,
  "useFaceApi": false,
  "useAuthenticityCheck": true,
  "checkHologram": false,
  "generateNumericCodes": true,
  "strictBarcodeDigitalSignatureCheck": false,
  "selectLongestNames": true,
  "generateDTCVC": false,
  "strictDLCategoryExpiry": true,
  "generateAlpha2Codes": false,
  "disableAuthResolutionFilter": true,
  "strictSecurityChecks": false,
  "returnTransliteratedFields": true,
  "measureSystem": 1,
  "barcodeParserType": 3,
  "perspectiveAngle": 4,
  "minDPI": 5,
  "imageDpiOutMax": 6,
  "forceDocID": 6,
  "pdfPagesLimit": 7,
  "forceDocFormat": 3,
  "shiftExpiryDate": 9,
  "minimalHolderAge": 10,
  "imageOutputMaxHeight": 11,
  "imageOutputMaxWidth": 12,
  "processAuth": 13,
  "convertCase": 3,
  "logLevel": "FatalError",
  "mrzDetectMode": 1,
  "dateFormat": "test1",
  "scenario": "Mrz",
  "captureButtonScenario": "Locate",
  "timeout": 15,
  "timeoutFromFirstDetect": 16,
  "timeoutFromFirstDocType": 17,
  "documentAreaMin": 18,
  "timeoutLiveness": 19,
  "documentIDList": [1, 2, 3],
  "barcodeTypes": [4, 5, 6],
  "fieldTypesFilter": [7, 8, 9],
  "resultTypeOutput": [10, 9, 8],
  "mrzFormatsFilter": ["1x30", "3x30", "2x30"],
  "documentGroupFilter": [135, 136, 137],
  "lcidIgnoreFilter": [10011, 1078, 1052],
  "lcidFilter": [1118, 5121, 15361],
  "imageQA": imageQA,
  "rfidParams": rfidParams,
  "faceApiParams": faceApiParams,
  "backendProcessingConfig": backendProcessingConfig,
  "authenticityParams": authenticityParams,
  "customParams": { "test1": true, "test2": 1, "test3": "test" },
  "checkFilters": { "checkAuth": filterObject },
}
export var font1 = { "name": "AppleSDGothicNeo-Thin", "size": 10, "style": 2 }
export var font2 = { "name": "Copperplate-Light", "size": 20, "style": 1 }
export var customizationColors = {
  "rfidProcessingScreenBackground": 0xff000000,
  "rfidProcessingScreenHintLabelText": 0xff000001,
  "rfidProcessingScreenHintLabelBackground": 0xff000002,
  "rfidProcessingScreenProgressLabelText": 0xff000003,
  "rfidProcessingScreenProgressBar": 0xff000004,
  "rfidProcessingScreenProgressBarBackground": 0xff000005,
  "rfidProcessingScreenResultLabelText": 0xff000006,
  "rfidProcessingScreenLoadingBar": 0xff000007,
  "rfidEnableNfcTitleText": 0xff000008,
  "rfidEnableNfcDescriptionText": 0xff000009,
  "rfidEnableNfcButtonText": 0xff000010,
  "rfidEnableNfcButtonBackground": 0xff000011,
}
export var customizationFonts = {
  "rfidProcessingScreenHintLabel": font1,
  "rfidProcessingScreenProgressLabel": font2,
  "rfidProcessingScreenResultLabel": font1,
  "rfidEnableNfcTitleText": font2,
  "rfidEnableNfcDescriptionText": font1,
  "rfidEnableNfcButtonText": font2,
}
export var customizationImages = {
  "rfidProcessingScreenFailureImage": img1,
  "rfidEnableNfcImage": img2,
}
export var customization = {
  "showStatusMessages": true,
  "showResultStatusMessages": false,
  "showHelpAnimation": true,
  "showNextPageAnimation": false,
  "showBackgroundMask": true,
  "cameraFrameBorderWidth": 1,
  "cameraFrameLineLength": 2,
  "cameraFrameShapeType": 1,
  "cameraFrameOffsetWidth": 3,
  "status": "test1",
  "resultStatus": "test2",
  "multipageButtonText": "test3",
  "cameraFrameDefaultColor": 0xff000000,
  "cameraFrameActiveColor": 0xff000001,
  "statusTextColor": 0xff000002,
  "resultStatusTextColor": 0xff000003,
  "resultStatusBackgroundColor": 0xff000004,
  "multipageButtonBackgroundColor": 0xff000005,
  "tintColor": 0xff000006,
  "activityIndicatorColor": 0xff000007,
  "statusBackgroundColor": 0xff000008,
  "cameraPreviewBackgroundColor": 0xff000009,
  "backgroundMaskColor": 0xff000010,
  "multipageButtonTextColor": 0xff000011,
  "statusPositionMultiplier": 0.5,
  "resultStatusPositionMultiplier": 1.5,
  "toolbarSize": 2.5,
  "backgroundMaskAlpha": 3.5,
  "customStatusPositionMultiplier": 4.5,
  "cameraFrameVerticalPositionMultiplier": 5.5,
  "cameraFrameLandscapeAspectRatio": 6.5,
  "cameraFramePortraitAspectRatio": 7.5,
  "cameraFrameCornerRadius": 8.5,
  "livenessAnimationPositionMultiplier": 9.5,
  "nextPageAnimationStartDelay": 10.5,
  "nextPageAnimationEndDelay": 11.5,
  "activityIndicatorPortraitPositionMultiplier": 12.5,
  "activityIndicatorLandscapePositionMultiplier": 13.5,
  "cameraPreviewVerticalPositionMultiplier": 14.5,
  "multipageAnimationFrontImage": img1,
  "multipageAnimationBackImage": img2,
  "borderBackgroundImage": img3,
  "helpAnimationImage": img1,
  "closeButtonImage": img2,
  "captureButtonImage": img3,
  "cameraSwitchButtonImage": img1,
  "torchButtonOnImage": img2,
  "torchButtonOffImage": img3,
  "changeFrameButtonExpandImage": img1,
  "changeFrameButtonCollapseImage": img2,
  "livenessAnimationImage": img3,
  "multipageButtonImage": img1,
  "customLabelStatus": "test3",
  "cameraFrameLineCap": 2,
  "uiCustomizationLayer": { "test": "test" },
  "statusTextFont": font1,
  "resultStatusTextFont": font2,
  "multipageButtonTextFont": font1,
  "helpAnimationImageContentMode": 0,
  "multipageAnimationFrontImageContentMode": 1,
  "multipageAnimationBackImageContentMode": 2,
  "livenessAnimationImageContentMode": 3,
  "borderBackgroundImageContentMode": 4,
  "helpAnimationImageMatrix": [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
  "multipageAnimationFrontImageMatrix": [
    2.1,
    2.2,
    2.3,
    2.4,
    2.5,
    2.6,
    2.7,
    2.8,
    2.9,
  ],
  "multipageAnimationBackImageMatrix": [
    3.1,
    3.2,
    3.3,
    3.4,
    3.5,
    3.6,
    3.7,
    3.8,
    3.9,
  ],
  "livenessAnimationImageMatrix": [4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9],
  "borderBackgroundImageMatrix": [5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9],
  "colors": customizationColors,
  "fonts": customizationFonts,
  "images": customizationImages,
}
export var cameraSize = { "width": 0, "height": 1 }
export var functionality = {
  "pictureOnBoundsReady": true,
  "showTorchButton": false,
  "showCloseButton": true,
  "videoCaptureMotionControl": false,
  "showCaptureButton": true,
  "showChangeFrameButton": false,
  "showSkipNextPageButton": true,
  "useAuthenticator": true,
  "skipFocusingFrames": true,
  "showCameraSwitchButton": false,
  "displayMetadata": true,
  "isZoomEnabled": false,
  "isCameraTorchCheckDisabled": true,
  "recordScanningProcess": false,
  "manualMultipageMode": true,
  "singleResult": false,
  "torchTurnedOn": false,
  "preventScreenRecording": true,
  "showCaptureButtonDelayFromDetect": 0,
  "showCaptureButtonDelayFromStart": 1,
  "rfidTimeout": 2,
  "forcePagesCount": 3,
  "orientation": 1,
  "captureMode": 2,
  "cameraMode": 0,
  "cameraPositionIOS": 1,
  "cameraFrame": "id1",
  "btDeviceName": "test",
  "zoomFactor": 0.5,
  "exposure": 1.5,
  "videoRecordingSizeDownscaleFactor": 2.5,
  "excludedCamera2Models": ["test1", "test2", "test3"],
  "cameraSize": cameraSize,
  "videoSessionPreset": 6,
}
export var eDLDataGroups = {
  "DG1": true,
  "DG2": false,
  "DG3": true,
  "DG4": false,
  "DG5": true,
  "DG6": false,
  "DG7": true,
  "DG8": false,
  "DG9": true,
  "DG10": false,
  "DG11": true,
  "DG12": false,
  "DG13": true,
  "DG14": false,
}
export var ePassportDataGroups = {
  "DG1": true,
  "DG2": false,
  "DG3": true,
  "DG4": false,
  "DG5": true,
  "DG6": false,
  "DG7": true,
  "DG8": false,
  "DG9": true,
  "DG10": false,
  "DG11": true,
  "DG12": false,
  "DG13": true,
  "DG14": false,
  "DG15": true,
  "DG16": false,
}
export var eIDDataGroups = {
  "DG1": true,
  "DG2": false,
  "DG3": true,
  "DG4": false,
  "DG5": true,
  "DG6": false,
  "DG7": true,
  "DG8": false,
  "DG9": true,
  "DG10": false,
  "DG11": true,
  "DG12": false,
  "DG13": true,
  "DG14": false,
  "DG15": true,
  "DG16": false,
  "DG17": true,
  "DG18": false,
  "DG19": true,
  "DG20": false,
  "DG21": true,
}
export var dtcDataGroup = {
  "DG17": true,
  "DG18": false,
  "DG22": false,
  "DG23": true,
  "DG24": false,
}
export var rfidScenario = {
  "paceStaticBinding": true,
  "onlineTA": false,
  "writeEid": true,
  "universalAccessRights": false,
  "authorizedRestrictedIdentification": true,
  "auxVerificationCommunityID": false,
  "auxVerificationDateOfBirth": true,
  "skipAA": false,
  "strictProcessing": true,
  "pkdDSCertPriority": false,
  "pkdUseExternalCSCA": true,
  "trustedPKD": false,
  "passiveAuth": true,
  "useSFI": false,
  "readEPassport": true,
  "readEID": false,
  "readEDL": true,
  "authorizedSTSignature": false,
  "authorizedSTQSignature": true,
  "authorizedWriteDG17": false,
  "authorizedWriteDG18": true,
  "authorizedWriteDG19": false,
  "authorizedWriteDG20": true,
  "authorizedWriteDG21": false,
  "authorizedVerifyAge": true,
  "authorizedVerifyCommunityID": false,
  "authorizedPrivilegedTerminal": true,
  "authorizedCANAllowed": false,
  "authorizedPINManagement": true,
  "authorizedInstallCert": false,
  "authorizedInstallQCert": true,
  "applyAmendments": false,
  "autoSettings": true,
  "proceedReadingAlways": false,
  "readDTC": true,
  "mrzStrictCheck": false,
  "loadCRLFromRemote": true,
  "independentSODStatus": false,
  "readingBuffer": -1,
  "onlineTAToSignDataType": 3,
  "defaultReadingBufferSize": 2,
  "signManagementAction": 3,
  "profilerType": 2,
  "authProcType": 3,
  "baseSMProcedure": 4,
  "pacePasswordType": 5,
  "terminalType": 1,
  "password": "test1",
  "pkdPA": "test2",
  "pkdEAC": "test3",
  "mrz": "test4",
  "eSignPINDefault": "test5",
  "eSignPINNewValue": "test6",
  "cardAccess": "test7",
  "mrzHash": "test8",
  "documentNumber": "test9",
  "dateOfBirth": "test10",
  "dateOfExpiry": "test11",
  "eDLDataGroups": eDLDataGroups,
  "ePassportDataGroups": ePassportDataGroups,
  "eIDDataGroups": eIDDataGroups,
  "dtcDataGroups": dtcDataGroup,
}

export var initConfig = {
  "delayedNNLoad": false,
  "licenseUpdate": true,
  "licenseUpdateTimeout": 1.5,
  "customDb": img1,
  "blackList": { "key1": "val1", "key2": "val2", "key3": "val3" },
  "databasePath": "test",
  "license": img2,
  "useBleDevice": true,
}
export var onlineProcessingConfig = {
  "mode": 1,
  "url": "test",
  "imageFormat": 1,
  "imageCompressionQuality": 1.5,
  "processParams": processParams,
  "requestHeaders": { "key1": "val1", "key2": "val2", "key3": "val3" },
}
export var imageInputData = { "image": img1, "light": 128, "pageIndex": 2 }
export var recognizeConfig = {
  "scenario": "Mrz",
  "livePortrait": img1,
  "extPortrait": img2,
  "oneShotIdentification": true,
  "dtc": img1,
  "image": img3,
  "data": img1,
  "images": [img1, img2, img3],
  "imageInputData": [imageInputData, imageInputData, imageInputData],
}
export var recognizeConfig2 = {
  "onlineProcessingConfig": onlineProcessingConfig,
  "livePortrait": img1,
  "extPortrait": img2,
  "oneShotIdentification": true,
  "image": img3,
  "data": img1,
  "images": [img1, img2, img3],
  "imageInputData": [imageInputData, imageInputData, imageInputData],
}
export var scannerConfig = {
  "scenario": "Mrz",
  "onlineProcessingConfig": onlineProcessingConfig,
  "livePortrait": img1,
  "extPortrait": img2,
  "cameraId": 1,
}

export var documentsDatabase = {
  "databaseID": "test1",
  "version": "test2",
  "date": "test3",
  "databaseDescription": "test4",
  "countriesNumber": 1,
  "documentsNumber": 2,
  "size": 3,
}
export var docReaderVersion = {
  "api": "test1",
  "core": "test2",
  "coreMode": "test3",
  "database": documentsDatabase,
}
export var docReaderScenario = {
  "uvTorch": true,
  "frameOrientation": 2,
  "faceExt": false,
  "multiPageOff": false,
  "seriesProcessMode": true,
  "frameKWHLandscape": 0.5,
  "frameKWHPortrait": 1.5,
  "frameKWHDoublePageSpreadPortrait": 2.5,
  "frameKWHDoublePageSpreadLandscape": 3.5,
  "name": "test1",
  "caption": "test2",
  "description": "test3",
  "manualCrop": false,
}
export var license = {
  "expiryDate": "test1",
  "countryFilter": ["test2", "test3", "test4"],
  "isRfidAvailable": true,
}
export var docReaderException = { "code": 1, "message": "test1" }
export var rfidException = { "code": 2, "message": "test2" }
export var prepareProgress = { "downloadedBytes": 1, "totalBytes": 2, "progress": 50 }

export var authenticityElement = {
  "status": 1,
  "elementType": 2,
  "elementDiagnose": 3,
  "elementTypeName": "Photo element",
  "elementDiagnoseName": "Error of internal data processing",
}
export var authenticityCheck = {
  "type": 1,
  "status": 2,
  "typeName": "UV dull paper check",
  "pageIndex": 3,
  "elements": [authenticityElement, authenticityElement, authenticityElement],
}
export var authenticityResult = {
  "status": 2,
  "checks": [authenticityCheck, authenticityCheck, authenticityCheck],
}
export var pdf417Info = { "errorLevel": 2, "columns": 3, "rows": 4 }
export var barcodeField = {
  "barcodeType": 5,
  "status": -6001,
  "pageIndex": 2,
  "pdf417Info": pdf417Info,
  "data": img1,
}
export var barcodeResult = {
  "fields": [barcodeField, barcodeField, barcodeField],
}
export var rect = { "bottom": 0, "top": 1, "left": 2, "right": 3 }
export var imageQuality = {
  "featureType": 1,
  "result": 2,
  "type": 3,
  "boundRects": [rect, rect, rect],
}
export var imageQualityGroup = {
  "count": 1,
  "result": 2,
  "pageIndex": 3,
  "imageQualityList": [imageQuality, imageQuality, imageQuality],
}
export var accessControlProcedureType = {
  "activeOptionIdx": 1,
  "type": 2,
  "status": 1,
  "notifications": [1, 2, 3],
}
export var fileData = { "data": "test", "length": 2, "type": 3, "status": 4 }
export var certificateData = { "data": "test", "length": 1 }
export var securityObjectCertificates = { "securityObject": certificateData }
export var file = {
  "fileData": fileData,
  "fileID": "test1",
  "notifications": [1, 2, 3],
  "pAStatus": 1,
  "readingStatus": 2,
  "readingTime": 3,
  "type": 4,
  "typeName": "Biometry - Iris Data (DG4)",
  "docFieldsText": [4, 5, 6],
  "docFieldsGraphics": [7, 8, 9],
  "docFieldsOriginals": [10, 11, 12],
  "certificates": securityObjectCertificates,
}
export var application = {
  "applicationID": "test1",
  "dataHashAlgorithm": "test2",
  "files": [file, file, file],
  "status": 1,
  "type": 2,
  "unicodeVersion": "test3",
  "version": "test4",
}
export var rfidValue = {
  "data": "test1",
  "length": 1,
  "status": 2,
  "type": 3,
  "format": "test2",
}
export var attribute = { "type": "test", "value": rfidValue }
export var authority = {
  "attributes": [attribute, attribute, attribute],
  "data": "test",
  "friendlyName": rfidValue,
}
export var cardProperties = {
  "aTQA": 1,
  "bitRateR": 2,
  "bitRateS": 3,
  "chipTypeA": 4,
  "mifareMemory": 5,
  "rfidType": 6,
  "sAK": 7,
  "support4": true,
  "supportMifare": false,
  "aTQB": "test1",
  "aTR": "test2",
  "baudrate1": "test3",
  "baudrate2": "test4",
  "uID": "test5",
}
export var extension = { "data": "test1", "type": "test2" }
export var rfidValidity = { "notAfter": rfidValue, "notBefore": rfidValue }
export var certificateChain = {
  "type": 1,
  "extensions": [extension, extension, extension],
  "fileName": rfidValue,
  "issuer": authority,
  "notifications": [1, 2, 3],
  "origin": 2,
  "paStatus": 3,
  "serialNumber": "test1",
  "signatureAlgorithm": "test2",
  "subject": authority,
  "subjectPKAlgorithm": "test3",
  "validity": rfidValidity,
  "version": 4,
}
export var dataField = { "data": "test", "fieldType": 1 }
export var signerInfo = {
  "dataToHash": "test1",
  "digestAlgorithm": "test2",
  "version": 1,
  "paStatus": 2,
  "signatureAlgorithm": "test3",
  "issuer": authority,
  "serialNumber": rfidValue,
  "signature": rfidValue,
  "subjectKeyIdentifier": rfidValue,
  "signedAttributes": [extension, extension, extension],
  "certificateChain": [certificateChain, certificateChain, certificateChain],
  "notifications": [1, 2, 3],
}
export var securityObject = {
  "fileReference": 1,
  "objectType": "test",
  "version": 2,
  "signerInfos": [signerInfo, signerInfo, signerInfo],
  "notifications": [1, 2, 3],
}
export var rfidSessionData = {
  "accessControls": [
    accessControlProcedureType,
    accessControlProcedureType,
    accessControlProcedureType,
  ],
  "applications": [application, application, application],
  "securityObjects": [securityObject, securityObject, securityObject],
  "dataFields": [dataField, dataField, dataField],
  "dataGroups": [1, 2, 3],
  "cardProperties": cardProperties,
  "totalBytesReceived": 1,
  "totalBytesSent": 2,
  "status": 1,
  "extLeSupport": 1,
  "processTime": 4,
}
export var bytesData = { "data": "test", "length": 1, "status": 2, "type": 3 }
export var vdsncData = {
  "type": "test1",
  "version": 1,
  "issuingCountry": "test2",
  "message": { "key1": "val1", "key2": "val2", "key3": "val3" },
  "signatureAlgorithm": "test3",
  "signature": bytesData,
  "certificate": bytesData,
  "certificateChain": [certificateChain, certificateChain, certificateChain],
  "notifications": [3000000001, 3000000002, 3000000003],
}
export var opticalStatus = {
  "overallStatus": 0,
  "mrz": 1,
  "text": 2,
  "docType": 0,
  "security": 1,
  "imageQA": 2,
  "expiry": 0,
  "vds": 1,
  "pagesCount": 3,
}
export var rfidStatus = {
  "overallStatus": 0,
  "pa": 1,
  "ca": 2,
  "aa": 0,
  "ta": 1,
  "bac": 2,
  "pace": 0,
}
export var resultsStatus = {
  "overallStatus": 0,
  "optical": 1,
  "rfid": 2,
  "portrait": 0,
  "stopList": 1,
  "detailsOptical": opticalStatus,
  "detailsRFID": rfidStatus,
}
export var comparison = { "sourceTypeLeft": 0, "sourceTypeRight": 1, "status": 2 }
export var graphicField = {
  "sourceType": 0,
  "fieldType": 201,
  "fieldName": "Portrait",
  "light": 128,
  "lightName": "UV",
  "pageIndex": 3,
  "originalPageIndex": 4,
  "value": img1,
  "fieldRect": rect,
}
export var graphicResult = {
  "fields": [graphicField, graphicField, graphicField],
}
export var rfidOrigin = { "dg": 1, "dgTag": 2, "entryView": 3, "tagEntry": 4 }
export var symbol = { "rect": rect, "code": 1, "probability": 2 }
export var validity = { "sourceType": 1, "status": 2 }
export var value = {
  "sourceType": 3,
  "value": "test1",
  "originalValue": "test2",
  "pageIndex": 2,
  "boundRect": rect,
  "rfidOrigin": rfidOrigin,
  "originalSymbols": [symbol, symbol, symbol],
  "probability": 1,
}
export var textField = {
  "fieldType": 1,
  "fieldName": "Issuing state code",
  "lcid": 10011,
  "lcidName": "Abkhazian (Cyrillic)",
  "value": "test3",
  "getValue": value,
  "values": [value, value, value],
  "status": 2,
  "comparisonList": [comparison, comparison, comparison],
  "validityList": [validity, validity, validity],
  "comparisonStatus": 0,
  "validityStatus": 1,
}
export var textSource = {
  "sourceType": validity["sourceType"],
  "source": "sourceType",
  "validityStatus": 1,
}
export var documentReaderTextSource2 = {
  "sourceType": comparison["sourceTypeLeft"],
  "source": "sourceTypeLeft",
  "validityStatus": 1,
}
export var documentReaderTextSource3 = {
  "sourceType": comparison["sourceTypeRight"],
  "source": "sourceTypeRight",
  "validityStatus": 1,
}
export var textResult = {
  "status": 0,
  "comparisonStatus": 1,
  "validityStatus": 2,
  "availableSourceList": [
    textSource,
    documentReaderTextSource2,
    documentReaderTextSource3,
  ],
  "fields": [textField, textField, textField],
}
export var documentType = {
  "name": "test1",
  "documentID": 1,
  "ICAOCode": "test2",
  "FDSID": [1, 2, 3],
  "dType": 11,
  "dFormat": 2,
  "dMRZ": true,
  "isDeprecated": false,
  "dDescription": "test3",
  "dYear": "test4",
  "dCountryName": "test5",
  "pageIndex": 3,
}
export var coordinate = { "x": 1, "y": 2 }
export var position = {
  "docFormat": 0,
  "resultStatus": 1,
  "width": 2,
  "height": 3,
  "angle": 0.5,
  "dpi": 4,
  "inverse": 5,
  "perspectiveTr": 6,
  "objArea": 7,
  "objIntAngleDev": 8,
  "pageIndex": 9,
  "center": coordinate,
  "leftTop": coordinate,
  "leftBottom": coordinate,
  "rightTop": coordinate,
  "rightBottom": coordinate,
}
export var transactionInfo = {
  "transactionId": "test1",
  "tag": "test2",
  "sessionLogFolder": "test3",
}
export var results = {
  "chipPage": 0,
  "processingFinishedStatus": 2,
  "elapsedTime": 3,
  "elapsedTimeRFID": 4,
  "morePagesAvailable": 5,
  "graphicResult": graphicResult,
  "textResult": textResult,
  "documentPosition": [position],
  "barcodePosition": [position, position],
  "mrzPosition": [position, position, position],
  "imageQuality": [imageQualityGroup, imageQualityGroup, imageQualityGroup],
  "documentType": [documentType, documentType, documentType],
  "rawResult": "test2",
  "rfidSessionData": rfidSessionData,
  "authenticityResult": authenticityResult,
  "barcodeResult": barcodeResult,
  "status": resultsStatus,
  "vdsncData": vdsncData,
  "dtcData": img1,
  "transactionInfo": transactionInfo,
}

export var rfidNotification = {
  "notificationCode": 65536,
  "dataFileType": 1,
  "progress": 2,
}
export var paAttribute = { "type": "test1", "value": "test2" }
export var paResourcesIssuer = {
  "data": img1,
  "friendlyName": "test",
  "attributes": [paAttribute, paAttribute, paAttribute],
}
export var pkdCertificate = {
  "binaryData": img1,
  "resourceType": 0,
  "privateKey": img2,
}
export var taChallenge = {
  "data": img1,
  "auxPCD": "test1",
  "challengePICC": "test2",
  "hashPK": "test3",
  "idPICC": "test4",
}
export var tccParams = {
  "serviceUrlTA": "test1",
  "serviceUrlPA": "test2",
  "pfxCertUrl": "test3",
  "pfxPassPhrase": "test4",
  "pfxCert": img1,
}
